extends:
  - "react-app"
  - "prettier"
  - "prettier/react"
  - "prettier/@typescript-eslint"
rules:
  "jsx-a11y/anchor-is-valid":
    - error
    - components:
        - "Link"
      specialLink:
        - "hrefLeft"
        - "hrefRight"
      aspects:
        - "invalidHref"
        - "preferButton"
