extends:
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
      allowHigherOrderFunctions: true
      allowTypedFunctionExpressions: true
