extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:jsx-a11y/recommended"
  - "prettier"
rules:
  "react/react-in-jsx-scope": "off"
  "react/prop-types": "off"
  "jsx-a11y/anchor-is-valid":
    - error
    - components:
        - "Link"
      specialLink:
        - "hrefLeft"
        - "hrefRight"
      aspects:
        - "invalidHref"
        - "preferButton"
settings:
  react:
    "version": "detect"
