extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/stylistic"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "plugin:jsx-a11y/recommended"
  - "plugin:@next/next/recommended"
  - "prettier"
plugins:
  - "import"
rules:
  "@typescript-eslint/consistent-type-imports": "error"
  "import/order":
    - "error"
    - alphabetize:
        order: "asc"
      warnOnUnassignedImports: true
  "react/react-in-jsx-scope": "off"
  "react/prop-types": "off"
  "jsx-a11y/anchor-is-valid":
    - error
    - components:
        - "Link"
      specialLink:
        - "hrefLeft"
        - "hrefRight"
      aspects:
        - "invalidHref"
        - "preferButton"
settings:
  react:
    "version": "detect"
overrides:
  - files:
      - next.config.js
    env:
      node: true
