name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        uses: docker://node:14.16.1-alpine
        with:
          entrypoint: yarn
          args: install
      - name: Lint
        uses: docker://node:14.16.1-alpine
        with:
          entrypoint: yarn
          args: lint
      - name: Build
        uses: docker://node:14.16.1-alpine
        with:
          entrypoint: yarn
          args: build
      - name: Deploy
        if: contains(github.ref, 'refs/heads/develop')
        uses: ./.github/actions/deploy
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          DIRECTORY: out
          USER: Chris Shepherd <chris@chrisshepherd.me>
